### ISSUE TITLE
'nvim-ts-rainbow' works only when manually enabled

### ISSUE THREAD

**Issue by Dice21** [askfiy/nvim#10]
I used this config but the rainbow parentheses doesn't work at the time I open any buffer. Using `TSEnable rainbow` can enabled it manually.

**Comment by askfiy** [comment]
ok, i'll fix it later...

**Comment by askfiy** [comment]
It seems correct on my side, did you change some lazyload conditions?

**Comment by Dice21** [comment]
> It seems correct on my side, did you change some lazyload conditions?

I recloned the config and made few changes to it. I have changed `download_source`  and disabled some plugins in plugins.lua. Does the changes in plugins.lua matter?

**Comment by askfiy** [comment]
I need the info in plugins.lua...

Also the information in nv_treesitter.lua is needed.

**Comment by Dice21** [comment]
> I need the info in plugins.lua...
> 
> Also the information in nv_treesitter.lua is needed.
> 
> can you upload your config

Ok. I have uploaded it at https://github.com/Dice21/nvim_temp.

**Comment by askfiy** [comment]
You can try deleting the after of rainbow plug-in.Try it, it should work.

**Comment by Dice21** [comment]
> You can try deleting the after of rainbow plug-in.Try it, it should work.

Yes it works for me. I really appreciate it.
