### ISSUE TITLE
Always trigger an error while opening a file.

### ISSUE THREAD

**Issue by BreakingLead** [askfiy/nvim#15]
![image](https://user-images.githubusercontent.com/30070684/178138589-efbde122-1206-4a47-abdd-ad184fa3a2ce.png)
I didn't modify anything except lua/core/mapping.lua file. Every time I open a file which can be attached by a lsp server, it responses an error message like this.

**Comment by askfiy** [comment]
I need your nv_nvim-lsp-installer.lua configuration file.

Obviously this error comes from a certain key you have modified.

**Comment by BreakingLead** [comment]
I found that I was still using outdated neovim so I updated it and it works.
But I found a new problem and I'm trying to fix it.
Thanks!
