### ISSUE TITLE
你好 请问为啥按k向上移动的时候会有延迟呢

### ISSUE THREAD

**Issue by Jinl-k** [askfiy/nvim#16]
如果慢点按k向上移动的时候会有大概1s延迟，但是按j向下移动就不会有延迟

**Comment by askfiy** [comment]
我将 k 重新映射成了 gk. 你可以在 mapping.lua 中查看，删除他们试试？ 我认为这不是该问题的主要原因。你是否安装过一些平滑移动的插件呢？

**Comment by Jinl-k** [comment]
哈哈 删除之后确实有所好转，谢谢你啦> 我将 k 重新映射成了 gk. 你可以在 mapping.lua 中查看，删除他们试试？ 我认为这不是该问题的主要原因。你是否安装过一些平滑移动的插件呢？
