### ISSUE TITLE
你好 请问notify中ignore_message的编写规则是怎样的呢

### ISSUE THREAD

**Issue by Jinl-k** [askfiy/nvim#18]
有时候会出现这种格式的弹窗，`Client 1 quit with exit code 127 and signal 0`，
我想把这种消息屏蔽掉，但是这种消息里的数字是会变动的，所以我想在ignore_message里添加上这个规则: Client  ？ quit with exit code ？ and signal ？

请问这个？具体填什么的呢

**Comment by askfiy** [comment]
`Client %d+ quit with exit code %d+ and signal %d+`

**Comment by Jinl-k** [comment]
弄好了 多谢你啦
