### ISSUE TITLE
mapping of j and k when use snippets

### ISSUE THREAD

**Issue by shell-Raining** [askfiy/nvim#19]
When using the code snippet, if I press j, I want to be able to type j to the current position instead of moving the cursor down a line

![image](https://user-images.githubusercontent.com/111564053/186833590-c63c7f30-1090-489b-bfa6-1debd72304fc.png)

|
v

![image](https://user-images.githubusercontent.com/111564053/186833983-b369da97-97de-46c3-909a-dda8a0a21506.png)

so i think ... maybe you can change the mapping for j and k from mode v to x

By the way, where is your esc and ctrl keys on the keyboard?

**Comment by askfiy** [comment]
The mappings for moving snippets are `<tab>` and `<s-tab>`, you can modify them in vsnip.lua.

`<c-l> = ctrl + l`
`<esc> = esc`
`<m-l> = alt + l`

**Comment by shell-Raining** [comment]
> The mappings for moving snippets are `<tab>` and `<s-tab>`, you can modify them in vsnip.lua.
> 
> `<c-l> = ctrl + l` `<esc> = esc` `<m-l> = alt + l`

我英文可能表述的不是很清楚，当我输入一个snippet时候，比如说图中的for,然后我正处于第一个补全位置，假如我想把i变量改为j,这时候我输入j,我的光标会向下一行，而不是期望的i改变为j,正如第一张图片所示，所以我想可以将mapping.lua中的j和k的映射模式改一下，不要在select模式下映射了

**Comment by askfiy** [comment]
你可以自己改一下，我下个版本会发。

![image](https://user-images.githubusercontent.com/81478335/186858780-e29f7c61-90f3-417d-8e74-95b103c73bc8.png)

**Comment by askfiy** [comment]
谢谢改进 ..

**Comment by shell-Raining** [comment]
顺带想问一下大佬是不是把 CapsLock 和 CTRL 的位置调换了呢，我之前是把 esc 和 CapsLock 调换，用这个配置感觉有些奇怪

**Comment by askfiy** [comment]
没有换诶，不过我是 66 的小键盘。

**Comment by shell-Raining** [comment]
配置里面Ctrl用的特别多，所以我以为把他换到了一个方便够到的地方😂

**Comment by askfiy** [comment]
我是用手掌摁的 `<ctrl>`，而且键盘小手掌大所以我没啥不适应的 ..
