### ISSUE TITLE
some plugins not loaded.

### ISSUE THREAD

**Issue by AnasR7** [askfiy/nvim#20]
hey, this is a cool project for me. But when  I was about to install this Nvim Config with a new install. I got a bit problem with some of these plugins not loaded on start and when I check :PackerStatus there some packages are not loaded or need to be manual install.

![2022-09-10_09-01-56_1920x1080](https://user-images.githubusercontent.com/23519166/189464792-87fa6a91-8a52-4ddb-ba7c-6dc8b44bebed.png)

**Comment by askfiy** [comment]
Because they are set to delay loading, they will only be loaded when you press a specific key or enter a specific command. This does not affect the use, but will improve the loading speed.

**Comment by AnasR7** [comment]
okay, I get it thanks. but when I want to use toggleterm I cannot run bcz it is not loaded.
