### ISSUE TITLE
Error when Open float toggleterm

### ISSUE THREAD

**Issue by fuqianya** [askfiy/nvim#21]
Hi, askfiy

Thanks for sharing your great neovim config. 
However, I found an error when I open float toggleterm using your config:
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/45023083/195973126-c9ceb5be-e16d-48d5-9e0b-3c60816baa96.png">

Can you give me some suggestions to fix this error?

**Comment by askfiy** [comment]
What is your mapping for closing the terminal?

**Comment by fuqianya** [comment]
I just clone your config and install the plugins. So my mapping keys are all same with this repo.

**Comment by fuqianya** [comment]
I'm sorry. I had remove the mapping from <esc> to escape the terminal, so i met this error.
