### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JorgeMadson** [askfiy/nvim#25]
Sorry I am totally newbie at nvim, I installed this on a manjaro and got this error, I have no idea how to fix it.
Can I get a little help here?

![Screenshot_20230206_160519](https://user-images.githubusercontent.com/10890678/217101049-e105e757-0fc2-4d2c-9a44-70b6c0bcde1c.png)

**Comment by askfiy** [comment]
There is too little information, it is not convenient for me to locate.

If available, please provide your current commit number and try `git pull origin`

**Comment by JorgeMadson** [comment]
Okay let me clone again and re install.

**Comment by JorgeMadson** [comment]
I just removed the old nvim config put a new one from a clone now it is working! 
Thanks a lot!

**Comment by JorgeMadson** [comment]
I wanna gonna close the issue.
