### ISSUE TITLE
python lsp error

### ISSUE THREAD

**Issue by LicsDaSheng** [askfiy/nvim#33]
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/12297288/236613386-7bd72228-cdec-4cd2-b123-161517317050.png">
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/12297288/236613423-03e0433e-99c6-478c-8327-c14acda8b404.png">
<img width="680" alt="image" src="https://user-images.githubusercontent.com/12297288/236613550-87185272-61ee-439e-81bd-4de4560d342b.png">

**Comment by askfiy** [comment]
FIX: https://github.com/askfiy/nvim/commit/39ba1c475383945738c59dcdd30ee9ca2c1dc319
