### ISSUE TITLE
Could you integrate some telescope extensions?

### ISSUE THREAD

**Issue by zhuzhzh** [askfiy/nvim#6]
like zoxide, fzf, dap

  5     vim.cmd([[packadd telescope-fzf-native.nvim]])
  6     vim.cmd([[packadd telescope-project.nvim]])
  7     vim.cmd([[packadd telescope-frecency.nvim]])
  8     vim.cmd([[packadd telescope-zoxide]])

**Comment by askfiy** [comment]
I don't use them, but you can add them yourself.

**Comment by zhuzhzh** [comment]
I add telescope-zoxide, it doesn't work. it seems telescope can't find the extentions.

the functionality of zoxide is missed in your configuration. there is no way to switch in different directions with fuzzy method.

:Z  <fuzzy word>

**Comment by askfiy** [comment]
Is this related to plugin lazy loading?

I don't use zoxide, and I'm mostly happy with my current configuration. So I may not be able to help you.

This configuration mainly provides a function that most people use, it is not suitable for everyone.

**Comment by par4m** [comment]
> I add telescope-zoxide, it doesn't work. it seems telescope can't find the extentions.
> 
> the functionality of zoxide is missed in your configuration. there is no way to switch in different directions with fuzzy method.
> 
> :Z

Telescope-zoxide doesn't work like that, you're referring to the other zoxide(or z) plugin for vim which is invoked by `:Z`,
for telescope zoxide use `:Telescope zoxide list`

To lazy load (I use packer), just lazy load Telescope normally (keys or cmd) and load telescope-zoxide after it
```lua
use({
	"jvgrootveld/telescope-zoxide",
	after = "telescope.nvim",
	config = function()
		require("telescope").load_extension("zoxide")
	end,
})
```

**Comment by askfiy** [comment]
现在使用 Lazy.nvim 后，telescope 的依赖将更易于安装。因此我决定关闭这个问题 ...
