### ISSUE TITLE
highlight error

### ISSUE THREAD

**Issue by zhuzhzh** [askfiy/nvim#7]
packer.nvim: Error running config for catppuccin: /home/harriszh/.config/nvim/lua/utils/api/hi.lua:16: Vim(highlight)::E411: highlight group not found: BufferLineIndicator

I can find it in lua/configure/theme/catppuccin/highlights.lua.  but I don't know how to debug it

**Comment by askfiy** [comment]
This is because the cappuccin theme has been updated, and here are two solutions: 

1. change the plug-in address of catppucci in plugins.lua to askfiy/catppucci and delete the as statement 

2. Replace a different theme 

I don't like the color scheme of the new cappuccin... so I won't recomend it and use the older version instead

**Comment by askfiy** [comment]
[9da7084](https://github.com/askfiy/nvim/commit/d1ce766622d2d028cc9cfb9c34af170974a41823)

**Comment by zhuzhzh** [comment]
I just update to your the latest code.

 33     ["askfiy/catppuccin"] = { -- dark purple theme
 34         cond = options.colorscheme == "catppuccin",
 35     },

but it has the same issue.

**Comment by askfiy** [comment]
Maybe you should run the: LuaClearCache command?

**Comment by zhuzhzh** [comment]
`:LuaClearCache` is not found.
but I delete the dir of ~/.cache/nvim.

now when I input any command, cmp will report error.

```txt
:q
Error executing vim.schedule lua callback: ...riszh/.config/nvim/lua/configure/plugins/nv_nvim-cmp.lua:176: attempt to i
ndex a nil value
stack traceback:
        ...riszh/.config/nvim/lua/configure/plugins/nv_nvim-cmp.lua:176: in function 'format'
        ...are/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/entry.lua:280: in function 'callback'
        ...im/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/cache.lua:36: in function 'get_vim_item'
        ...are/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/entry.lua:195: in function 'get_view'
        ...packer/opt/nvim-cmp/lua/cmp/view/custom_entries_view.lua:131: in function 'open'
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/view.lua:110: in function 'open'
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/core.lua:325: in function 'fn'
        ...im/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/async.lua:41: in function <...im/site/pack/packer/opt/nvim-cmp
/lua/cmp/utils/async.lua:39>
:q
Error executing vim.schedule lua callback: ...riszh/.config/nvim/lua/configure/plugins/nv_nvim-cmp.lua:176: attempt to i
ndex a nil value
stack traceback:
        ...riszh/.config/nvim/lua/configure/plugins/nv_nvim-cmp.lua:176: in function 'format'
        ...are/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/entry.lua:280: in function 'callback'
        ...im/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/cache.lua:36: in function 'get_vim_item'
        ...are/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/entry.lua:195: in function 'get_view'
        ...packer/opt/nvim-cmp/lua/cmp/view/custom_entries_view.lua:131: in function 'open'
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/view.lua:110: in function 'open'
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/core.lua:325: in function 'fn'
        ...im/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/async.lua:41: in function <...im/site/pack/packer/opt/nvim-cmp
/lua/cmp/utils/async.lua:39>
```

**Comment by askfiy** [comment]
The problem is with Cmp-format, have you changed some configurations?

**Comment by zhuzhzh** [comment]
`vim_item.kind = string.format("%s %s", icons[options.icons_style][kind], kind)`

yes, I changed `options.lua` .

```vim
    icons_style = "lspkind",
```

**Comment by askfiy** [comment]
You can't set this up... because it's not lspkind, you should check the lspkind plug-in description and use it correctly.

**Comment by zhuzhzh** [comment]
actually, I don't need to use lspkind. but if I don't use it,  aerial will show up the info windows everytime nvim is invoked.

**Comment by zhuzhzh** [comment]
Okay, I found the issue.

aerial will heck if lspkind is installed. if it's, then it will show up the info windows.

After removing lspkind, it doesn't show any more.

**Comment by askfiy** [comment]
For me, I basically don't see the warning message for arial... also, can you try running :LuaCacheClear? I'm sorry, I really forgot this order.
