### ISSUE TITLE
aerial warning on icons

### ISSUE THREAD

**Issue by zhuzhzh** [askfiy/nvim#9]
Aerial: use lspkind to configure symbols instead of config value 'icons'

**Comment by askfiy** [comment]
lspkind I have used the configuration symbol before, and it is no different from manual configuration. You can modify the icon in utils / icons. lua. This warning should only appear once, and when you successfully install and restart Neovim, it should not appear again.

**Comment by zhuzhzh** [comment]
it will show every time nvim is opened. so I install lspkind theme later.

**Comment by askfiy** [comment]
Well, in that case, I think I should shut it down.
